[package]
name = "rights"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["rt", "net", "io-util", "time"] }
anyhow = "1"
rustix = { version = "1", features = ["net"] }
libc = "0.2"
chrono = "0.4"